# Comprehensive list of Indian Stocks for the platform
# Includes Nifty 50, Mid-Cap, and Penny Stocks

INDIAN_STOCKS_DATABASE = [
    # --- Nifty 50 (Large Cap) ---
    {"symbol": "RELIANCE", "name": "Reliance Industries Ltd", "sector": "Energy", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "TCS", "name": "Tata Consultancy Services", "sector": "Technology", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "HDFCBANK", "name": "HDFC Bank Ltd", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "INFY", "name": "Infosys Ltd", "sector": "Technology", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "ICICIBANK", "name": "ICICI Bank Ltd", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "HINDUNILVR", "name": "Hindustan Unilever Ltd", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "ITC", "name": "ITC Ltd", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "SBIN", "name": "State Bank of India", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "BHARTIARTL", "name": "Bharti Airtel Ltd", "sector": "Telecommunication", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "KOTAKBANK", "name": "Kotak Mahindra Bank", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "LT", "name": "Larsen & Toubro Ltd", "sector": "Construction", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "AXISBANK", "name": "Axis Bank Ltd", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "ASIANPAINT", "name": "Asian Paints Ltd", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "HCLTECH", "name": "HCL Technologies Ltd", "sector": "Technology", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "MARUTI", "name": "Maruti Suzuki India", "sector": "Automobile", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "TITAN", "name": "Titan Company Ltd", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "BAJFINANCE", "name": "Bajaj Finance Ltd", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "SUNPHARMA", "name": "Sun Pharmaceutical", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "TATAMOTORS", "name": "Tata Motors Ltd", "sector": "Automobile", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "ULTRACEMCO", "name": "UltraTech Cement Ltd", "sector": "Construction", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "WIPRO", "name": "Wipro Ltd", "sector": "Technology", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "LTIM", "name": "LTIMindtree Ltd", "sector": "Technology", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True, "base_price": 5000.0},
    {"symbol": "ONGC", "name": "Oil & Natural Gas Corp", "sector": "Energy", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "NTPC", "name": "NTPC Ltd", "sector": "Energy", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "POWERGRID", "name": "Power Grid Corp", "sector": "Energy", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "JSWSTEEL", "name": "JSW Steel Ltd", "sector": "Metals", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "TATASTEEL", "name": "Tata Steel Ltd", "sector": "Metals", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "ADANIENT", "name": "Adani Enterprises Ltd", "sector": "Services", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "ADANIPORTS", "name": "Adani Ports & SEZ", "sector": "Services", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "GRASIM", "name": "Grasim Industries", "sector": "Construction", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "COALINDIA", "name": "Coal India Ltd", "sector": "Metals", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "BAJAJ-AUTO", "name": "Bajaj Auto Ltd", "sector": "Automobile", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "TECHM", "name": "Tech Mahindra Ltd", "sector": "Technology", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "HINDALCO", "name": "Hindalco Industries", "sector": "Metals", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "DRREDDY", "name": "Dr. Reddy's Laboratories", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "M&M", "name": "Mahindra & Mahindra", "sector": "Automobile", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "CIPLA", "name": "Cipla Ltd", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "BPCL", "name": "Bharat Petroleum", "sector": "Energy", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "INDUSINDBK", "name": "IndusInd Bank Ltd", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "EICHERMOT", "name": "Eicher Motors Ltd", "sector": "Automobile", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "APOLLOHOSP", "name": "Apollo Hospitals", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "DIVISLAB", "name": "Divi's Laboratories", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "TATACONSUM", "name": "Tata Consumer Products", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "SBILIFE", "name": "SBI Life Insurance", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "HDFCLIFE", "name": "HDFC Life Insurance", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "BAJAJFINSV", "name": "Bajaj Finserv Ltd", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "BRITANNIA", "name": "Britannia Industries", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},
    {"symbol": "HEROMOTOCO", "name": "Hero MotoCorp Ltd", "sector": "Automobile", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": True, "is_nifty100": True},

    # --- Mid Cap Stocks (Growth) ---
    {"symbol": "ZOMATO", "name": "Zomato Ltd", "sector": "Technology", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": True, "base_price": 200.0},
    {"symbol": "PAYTM", "name": "One97 Communications", "sector": "Technology", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "NYKAA", "name": "FSN E-Commerce", "sector": "Technology", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "POLICYBZR", "name": "PB Fintech Ltd", "sector": "Technology", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "DELHIVERY", "name": "Delhivery Ltd", "sector": "Services", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "L&TFH", "name": "L&T Finance Holdings", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 150.0},
    {"symbol": "ABCAPITAL", "name": "Aditya Birla Capital", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "ASHOKLEY", "name": "Ashok Leyland Ltd", "sector": "Automobile", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "TVSMOTOR", "name": "TVS Motor Company", "sector": "Automobile", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "MRF", "name": "MRF Ltd", "sector": "Automobile", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "JUBLFOOD", "name": "Jubilant FoodWorks", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "DEVYANI", "name": "Devyani International", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "VARROC", "name": "Varroc Engineering", "sector": "Automobile", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "MOTHERSON", "name": "Samvardhana Motherson", "sector": "Automobile", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "BOSCHLTD", "name": "Bosch Ltd", "sector": "Automobile", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "PAGEIND", "name": "Page Industries", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "TRENT", "name": "Trent Ltd", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "ABFRL", "name": "Aditya Birla Fashion", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "BATAINDIA", "name": "Bata India Ltd", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "RELAXO", "name": "Relaxo Footwears", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "VOLTAS", "name": "Voltas Ltd", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "HAVELLS", "name": "Havells India Ltd", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "CROMPTON", "name": "Crompton Greaves", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "DIXON", "name": "Dixon Technologies", "sector": "Technology", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "AMBER", "name": "Amber Enterprises", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "POLYCAB", "name": "Polycab India", "sector": "Construction", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "KEI", "name": "KEI Industries", "sector": "Construction", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "ASTRAL", "name": "Astral Ltd", "sector": "Construction", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "SUPREMEIND", "name": "Supreme Industries", "sector": "Construction", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "PIDILITIND", "name": "Pidilite Industries", "sector": "Chemicals", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "SRF", "name": "SRF Ltd", "sector": "Chemicals", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "PIIND", "name": "PI Industries", "sector": "Chemicals", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "NAVINFLUOR", "name": "Navin Fluorine", "sector": "Chemicals", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "DEEPAKNTR", "name": "Deepak Nitrite", "sector": "Chemicals", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "TATACHEM", "name": "Tata Chemicals", "sector": "Chemicals", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "UPL", "name": "UPL Ltd", "sector": "Chemicals", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "COROMANDEL", "name": "Coromandel International", "sector": "Chemicals", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "CHAMBLFERT", "name": "Chambal Fertilisers", "sector": "Chemicals", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "GNFC", "name": "GNFC", "sector": "Chemicals", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},
    {"symbol": "GSFC", "name": "GSFC", "sector": "Chemicals", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False},

    # --- Penny Stocks & Small Cap (Under ₹50 or Small Cap) ---
    {"symbol": "YESBANK", "name": "Yes Bank Ltd", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 21.56},
    {"symbol": "IDEA", "name": "Vodafone Idea Ltd", "sector": "Telecommunication", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 11.15},
    {"symbol": "SUZLON", "name": "Suzlon Energy Ltd", "sector": "Energy", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 51.94},
    {"symbol": "RPOWER", "name": "Reliance Power Ltd", "sector": "Energy", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 35.69},
    {"symbol": "JPPOWER", "name": "Jaiprakash Power", "sector": "Energy", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 17.92},
    {"symbol": "GTLINFRA", "name": "GTL Infrastructure", "sector": "Telecommunication", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 1.25},
    {"symbol": "TRIDENT", "name": "Trident Ltd", "sector": "Textiles", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 27.00},
    {"symbol": "ALOKINDS", "name": "Alok Industries", "sector": "Textiles", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 15.72},
    {"symbol": "HFCL", "name": "HFCL Ltd", "sector": "Telecommunication", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 64.53},
    {"symbol": "RENUKA", "name": "Shree Renuka Sugars", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 26.04},
    {"symbol": "EASEMYTRIP", "name": "Easy Trip Planners", "sector": "Services", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 7.64},
    {"symbol": "IRFC", "name": "Indian Railway Finance", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 150.0},
    {"symbol": "RVNL", "name": "Rail Vikas Nigam", "sector": "Construction", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 250.0},
    {"symbol": "IRCON", "name": "Ircon International", "sector": "Construction", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 200.0},
    {"symbol": "NBCC", "name": "NBCC (India) Ltd", "sector": "Construction", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 120.0},
    {"symbol": "HUDCO", "name": "HUDCO", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 200.0},
    {"symbol": "IFCI", "name": "IFCI Ltd", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 40.0},
    {"symbol": "SOUTHBANK", "name": "South Indian Bank", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 30.0},
    {"symbol": "UCOBANK", "name": "UCO Bank", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 50.0},
    {"symbol": "CENTRALBK", "name": "Central Bank of India", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 60.0},
    {"symbol": "IOB", "name": "Indian Overseas Bank", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 60.0},
    {"symbol": "MAHABANK", "name": "Bank of Maharashtra", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 60.0},
    {"symbol": "PSB", "name": "Punjab & Sind Bank", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 60.0},
    {"symbol": "BOMDYEING", "name": "Bombay Dyeing", "sector": "Textiles", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 150.0},
    {"symbol": "RAYMOND", "name": "Raymond Ltd", "sector": "Textiles", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 1500.0},
    {"symbol": "WELSPUNIND", "name": "Welspun Living", "sector": "Textiles", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 150.0},
    {"symbol": "VGUARD", "name": "V-Guard Industries", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 350.0},
    {"symbol": "SYMPHONY", "name": "Symphony Ltd", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 900.0},
    {"symbol": "TTKPRESTIG", "name": "TTK Prestige", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 800.0},
    {"symbol": "VIPIND", "name": "VIP Industries", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 500.0},
    {"symbol": "CENTURYPLY", "name": "Century Plyboards", "sector": "Construction", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 700.0},
    {"symbol": "KAJARIACER", "name": "Kajaria Ceramics", "sector": "Construction", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 1200.0},
    {"symbol": "CERA", "name": "Cera Sanitaryware", "sector": "Construction", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 7000.0},
    {"symbol": "GREENPLY", "name": "Greenply Industries", "sector": "Construction", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 250.0},
    {"symbol": "LAOPALA", "name": "La Opala RG", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 300.0},
    {"symbol": "BOROLTD", "name": "Borosil Ltd", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 400.0},
    {"symbol": "HCG", "name": "Healthcare Global", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 350.0},
    {"symbol": "NH", "name": "Narayana Hrudayalaya", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 1200.0},
    {"symbol": "ASTERDM", "name": "Aster DM Healthcare", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 400.0},
    {"symbol": "KIMS", "name": "Krishna Institute", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 2000.0},
    {"symbol": "RAINBOW", "name": "Rainbow Children", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 1000.0},
    {"symbol": "METROPOLIS", "name": "Metropolis Healthcare", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 1500.0},
    {"symbol": "LALPATHLAB", "name": "Dr. Lal PathLabs", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 2500.0},
    {"symbol": "THYROCARE", "name": "Thyrocare Tech", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 600.0},
    {"symbol": "VIJAYA", "name": "Vijaya Diagnostic", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 600.0},
    {"symbol": "CDSL", "name": "CDSL", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 1500.0},
    {"symbol": "BSE", "name": "BSE Ltd", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 2500.0},
    {"symbol": "MCX", "name": "Multi Commodity Exch", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 3000.0},
    {"symbol": "IEX", "name": "Indian Energy Exch", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 150.0},
    {"symbol": "CAMS", "name": "CAMS", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 2800.0},
    {"symbol": "KFINTECH", "name": "KFin Technologies", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 600.0},
    {"symbol": "ANGELONE", "name": "Angel One Ltd", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 2500.0},
    {"symbol": "MOTILALOFS", "name": "Motilal Oswal Fin", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 1800.0},
    {"symbol": "ISEC", "name": "ICICI Securities", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 700.0},
    {"symbol": "IIFL", "name": "IIFL Finance", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 400.0},
    {"symbol": "JMFINANCIL", "name": "JM Financial", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 80.0},
    {"symbol": "EDELWEISS", "name": "Edelweiss Financial", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 70.0},
    {"symbol": "GEOJITFSL", "name": "Geojit Financial", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 70.0},
    {"symbol": "5PAISA", "name": "5Paisa Capital", "sector": "Financial Services", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 500.0},
    {"symbol": "SJVN", "name": "SJVN Ltd", "sector": "Energy", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 120.0},
    {"symbol": "NHPC", "name": "NHPC Ltd", "sector": "Energy", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 90.0},
    {"symbol": "NLCINDIA", "name": "NLC India Ltd", "sector": "Energy", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 230.0},
    {"symbol": "CESC", "name": "CESC Ltd", "sector": "Energy", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 130.0},
    {"symbol": "TORNTPOWER", "name": "Torrent Power", "sector": "Energy", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 1000.0},
    {"symbol": "ADANIENSOL", "name": "Adani Energy Solutions", "sector": "Energy", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": False, "is_nifty100": True, "base_price": 1000.0},
    {"symbol": "ADANIGREEN", "name": "Adani Green Energy", "sector": "Energy", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": False, "is_nifty100": True, "base_price": 1800.0},
    {"symbol": "ADANITRANS", "name": "Adani Transmission", "sector": "Energy", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": False, "is_nifty100": True, "base_price": 1000.0},
    {"symbol": "ATGL", "name": "Adani Total Gas", "sector": "Energy", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": False, "is_nifty100": True, "base_price": 900.0},
    {"symbol": "AWL", "name": "Adani Wilmar", "sector": "Consumer Goods", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 350.0},
    {"symbol": "NDTV", "name": "NDTV", "sector": "Media", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 200.0},
    {"symbol": "ZEEL", "name": "Zee Entertainment", "sector": "Media", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 150.0},
    {"symbol": "SUNTV", "name": "Sun TV Network", "sector": "Media", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 600.0},
    {"symbol": "PVRINOX", "name": "PVR INOX Ltd", "sector": "Media", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 1400.0},
    {"symbol": "SAREGAMA", "name": "Saregama India", "sector": "Media", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 350.0},
    {"symbol": "TIPSINDLTD", "name": "Tips Industries", "sector": "Media", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 400.0},
    {"symbol": "HATHWAY", "name": "Hathway Cable", "sector": "Media", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 20.0},
    {"symbol": "DEN", "name": "Den Networks", "sector": "Media", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 50.0},
    {"symbol": "TV18BRDCST", "name": "TV18 Broadcast", "sector": "Media", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 50.0},
    {"symbol": "NETWORK18", "name": "Network18 Media", "sector": "Media", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 90.0},
    {"symbol": "JUSTDIAL", "name": "Just Dial Ltd", "sector": "Services", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 900.0},
    {"symbol": "NAUKRI", "name": "Info Edge (India)", "sector": "Technology", "exchange": "NSE", "market_cap_category": "large", "is_nifty50": False, "is_nifty100": True, "base_price": 6000.0},
    {"symbol": "PERSISTENT", "name": "Persistent Systems", "sector": "Technology", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 3500.0},
    {"symbol": "COFORGE", "name": "Coforge Ltd", "sector": "Technology", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 6000.0},
    {"symbol": "MPHASIS", "name": "Mphasis Ltd", "sector": "Technology", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 2500.0},
    {"symbol": "LTTS", "name": "L&T Technology", "sector": "Technology", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 4500.0},
    {"symbol": "TATAELXSI", "name": "Tata Elxsi Ltd", "sector": "Technology", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 7000.0},
    {"symbol": "KPITTECH", "name": "KPIT Technologies", "sector": "Technology", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 1200.0},
    {"symbol": "CYIENT", "name": "Cyient Ltd", "sector": "Technology", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 1500.0},
    {"symbol": "ZENSARTECH", "name": "Zensar Technologies", "sector": "Technology", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 600.0},
    {"symbol": "SONATSOFTW", "name": "Sonata Software", "sector": "Technology", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 500.0},
    {"symbol": "INTELLECT", "name": "Intellect Design", "sector": "Technology", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 700.0},
    {"symbol": "MASTEK", "name": "Mastek Ltd", "sector": "Technology", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 2500.0},
    {"symbol": "TANLA", "name": "Tanla Platforms", "sector": "Technology", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 800.0},
    {"symbol": "ROUTE", "name": "Route Mobile", "sector": "Technology", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 1500.0},
    {"symbol": "AFFLE", "name": "Affle (India)", "sector": "Technology", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 1200.0},
    {"symbol": "HAPPSTMNDS", "name": "Happiest Minds", "sector": "Technology", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 800.0},
    {"symbol": "LATENTVIEW", "name": "Latent View", "sector": "Technology", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 400.0},
    {"symbol": "MAPMYINDIA", "name": "C.E. Info Systems", "sector": "Technology", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 1800.0},
    {"symbol": "RATEGAIN", "name": "RateGain Travel", "sector": "Technology", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 600.0},
    {"symbol": "NAZARA", "name": "Nazara Technologies", "sector": "Technology", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 800.0},
    {"symbol": "ECLERX", "name": "eClerx Services", "sector": "Technology", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 2000.0},
    {"symbol": "FSL", "name": "Firstsource Sol", "sector": "Technology", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 300.0},
    {"symbol": "BSOFT", "name": "Birlasoft Ltd", "sector": "Technology", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 600.0},
    {"symbol": "GLENMARK", "name": "Glenmark Pharma", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 800.0},
    {"symbol": "LUPIN", "name": "Lupin Ltd", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 1500.0},
    {"symbol": "AUROPHARMA", "name": "Aurobindo Pharma", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 1200.0},
    {"symbol": "BIOCON", "name": "Biocon Ltd", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 300.0},
    {"symbol": "TORNTPHARM", "name": "Torrent Pharma", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 2500.0},
    {"symbol": "ZYDUSLIFE", "name": "Zydus Lifesciences", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 900.0},
    {"symbol": "ALKEM", "name": "Alkem Laboratories", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 5000.0},
    {"symbol": "ABBOTINDIA", "name": "Abbott India", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 25000.0},
    {"symbol": "GLAXO", "name": "GlaxoSmithKline", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 2500.0},
    {"symbol": "PFIZER", "name": "Pfizer Ltd", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 4000.0},
    {"symbol": "SANOFI", "name": "Sanofi India", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 6500.0},
    {"symbol": "JBCHEPHARM", "name": "J.B. Chemicals", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 1500.0},
    {"symbol": "NATCOPHARM", "name": "Natco Pharma", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 1200.0},
    {"symbol": "IPCALAB", "name": "IPCA Laboratories", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "mid", "is_nifty50": False, "is_nifty100": False, "base_price": 1000.0},
    {"symbol": "LAURUSLABS", "name": "Laurus Labs", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 400.0},
    {"symbol": "GRANULES", "name": "Granules India", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 500.0},
    {"symbol": "FDC", "name": "FDC Ltd", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 400.0},
    {"symbol": "MARKSANS", "name": "Marksans Pharma", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 150.0},
    {"symbol": "MOREPENLAB", "name": "Morepen Labs", "sector": "Healthcare", "exchange": "NSE", "market_cap_category": "small", "is_nifty50": False, "is_nifty100": False, "base_price": 50.0},
]
